name: numbers
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.0.0
  # Bloc for state management
  flutter_bloc: ^7.2.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.3
  # Local cache
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
